services:

  mastr-tool:
    pull_policy: if_not_present
    image: mastr-tool:latest
    build: .
    container_name: mastr-tool
    user: 1000:1000
    restart: no
    environment:
      MASTR_FORCE_USING_EXISTING_DUMP: "false" # use existing dump and do not download
    volumes:
      - ${MASTR_CACHE_DIR}:/mastr/cache
      - ${MASTR_OUTPUT_DIR}:/mastr/output
    depends_on:
      - db

  mastr-static:
    pull_policy: if_not_present
    image: mastr-static:latest
    build: httpd-static
    container_name: mastr-static
    restart: on-failure
    volumes:
      - ${MASTR_OUTPUT_DIR}:/var/www/mastr-output/:ro
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - mastr-tool

  db:
    image: docker.io/postgres:16-bookworm
    restart: unless-stopped
    container_name: mastr-db
    environment:
      - POSTGRES_USER=mastr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mastr
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - mastr-database:/var/lib/postgresql/data

  # MaStR WebUI
  mastr-app:
    pull_policy: if_not_present
    image: mastr-app:latest
    build: ../mastr-app
    container_name: mastr-app
    restart: on-failure
    environment:
      MASTR_STATIC_URL: http://mastr-static:8080
      MASTR_STATIC_PUBLIC_URL: ${MASTR_STATIC_PUBLIC_URL}
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      - mastr-static

volumes:
  mastr-database: