services:
  mastr-tool:
    image: mastr-tool:latest
    pull_policy: "if_not_present"
    restart: unless-stopped
    environment:
      plop: "plop"
    volumes:
      - /datenpool/Share/Marktstammdatenregister/docker_cache:/mastr/cache
      - /datenpool/Share/Marktstammdatenregister/docker_output:/mastr/output

  db:
    image: docker.io/postgres:16-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mastr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mastr
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:15432:5432"

volumes:
  mastr-tool-enricher-cache: