services:
  mastr-tool:
    image: mastr-tool:latest
    build: .
    user: 1000:1000
    pull_policy: "if_not_present"
    restart: no
    environment:
      MASTR_NOT_CHECK_UPDATES: "true"
    volumes:
      - /datenpool/Share/Marktstammdatenregister/docker_cache:/mastr/cache
      - /datenpool/Share/Marktstammdatenregister/docker_output:/mastr/output
    depends_on:
      - db

  db:
    image: docker.io/postgres:16-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mastr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mastr
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  mastr-tool-enricher-cache: