services:

  mastr-tool:
    pull_policy: if_not_present
    image: mastr-tool:latest
    build: .
    container_name: mastr-tool
    restart: unless-stopped
    user: 1000:1000
    environment:
      MASTR_FORCE_USING_EXISTING_DUMP: "${MASTR_FORCE_USING_EXISTING_DUMP:-false}"
    volumes:
      - ${MASTR_CACHE_DIR}:/mastr/cache
      - ${MASTR_OUTPUT_DIR}:/mastr/output
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/postgres:18
    restart: unless-stopped
    container_name: mastr-db
    environment:
      - POSTGRES_USER=mastr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mastr
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGDATA=/var/lib/postgresql/18/data
    command: >
      postgres
      -c max_wal_size=2GB
      -c checkpoint_timeout=15min
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c wal_compression=on
      -c shared_buffers=256MB
      -c synchronous_commit=off
      -c bgwriter_lru_maxpages=200
      -c bgwriter_delay=50ms
    volumes:
      - mastr-database:/var/lib/postgresql/18/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mastr -d mastr" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mastr-database:
